SECRET_KEY = 'secret!'
DEBUG = True
DB_USERNAME = 'root'
DB_PASSWORD = 'pass'
BLOG_DATABASE_NAME = 'crud'
MARIA_D = '172.17.0.3'
SQLALCHEMY_DATABASE_URI = 'mysql://%s:%s@%s:3306/%s' %(DB_USERNAME,DB_PASSWORD,MARIA_D,BLOG_DATABASE_NAME)
#SQLALCHEMY_DATABASE_URI ='sqlite:////tmp/test.db'
