"""empty message

Revision ID: 191c44256204
Revises: be680d52f450
Create Date: 2015-12-28 22:30:46.478132

"""

# revision identifiers, used by Alembic.
revision = '191c44256204'
down_revision = 'be680d52f450'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'location')
    ### end Alembic commands ###
