"""empty message

Revision ID: be680d52f450
Revises: 21104df68684
Create Date: 2015-12-28 12:06:48.959497

"""

# revision identifiers, used by Alembic.
revision = 'be680d52f450'
down_revision = '21104df68684'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column(u'user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'last_seen')
    op.drop_column(u'user', 'about_me')
    op.drop_table('posts')
    ### end Alembic commands ###
