"""empty message

Revision ID: eb9dfe4806d5
Revises: 191c44256204
Create Date: 2015-12-28 22:43:06.745038

"""

# revision identifiers, used by Alembic.
revision = 'eb9dfe4806d5'
down_revision = '191c44256204'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('website', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    ### end Alembic commands ###
